### ISSUE TITLE
Service Worker Not being minified

### ISSUE THREAD

**Issue by logotip4ik** [vite-pwa/nuxt#62]
https://stackblitz.com/edit/nuxt-starter-l1gvkq?file=nuxt.config.ts

## Reproduction

1. `yarn && yarn run build`
2. `code .output/public/sw.js` stackblitz wont show and update `.output` directory? You need manually open it after each build

## Info
`strategies: 'injectManifest'` will inline `workbox` utils but then it won't minify the service worker itself. With `generateSW` strategy, vite will minify both `sw.js` and `workbox-*.js` files

**Comment by userquin** [comment]
@logotip4ik I'll review latest changes in Nuxt, it is weird, mode should be production and `injectManifest` should minify the sw (the pwa plugin includes `process.env.NODE_ENV="production"` via Vite define option in the custom build): https://github.com/vite-pwa/vite-plugin-pwa/blob/main/src/modules.ts#L95

**Comment by userquin** [comment]
anyway, your sw has errors: missing `race` and `debug` variables and error in L55

**Comment by logotip4ik** [comment]
> anyway, your sw has errors: missing `race` and `debug` variables and error in L55

I thought that they would be somehow inlined at the build time 😅. I took this example from vite-pwa website (https://vite-pwa-org.netlify.app/workbox/inject-manifest.html#network-first-strategy). Should i open pr to fix this ?

**Comment by userquin** [comment]
@logotip4ik found the problem: 
- by default Vite will use `esbuild` to minify, since we're using a custom Vite build to build the service worker, Vite will use `esbuild` since pwa plugin will not provide/change the `build.minify` option
-  `vite-plugin-pwa` is using `es` as default Rollup format to build the service worker, but Vite will not remove empty spaces https://vitejs.dev/config/build-options.html#build-minify:
   > Note the build.minify option does not minify whitespaces when using the 'es' format in lib mode, as it removes pure annotations and breaks tree-shaking.

You can change the format using `iife`, the service worker is minified but the code generated is wrong and will not work.

You can check it here in this SB fork : https://stackblitz.com/edit/nuxt-starter-al3pyt?file=nuxt.config.ts.
If you run `yarn build` the output will be on `server/public` folder, I've changed nitro `output.dir` and there is an issue on nitro about custom output (also tried with terser plugin with no luck).

**Comment by logotip4ik** [comment]
Can't reproduce with `@vite-pwa/nuxt@0.10.0`, `vite-plugin-pwa@0.20.1` and `vite@5.4.1`, now everything is minimized, so will close. Thanks!
